image:
  repository: ohmygaugh-crypto/baseline-react-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.

  tag: "20230822T154742"
imagePullSecrets: 
  - name: docker-pull-secret
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: "traefik"
  annotations:
    - cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: react.212.2.242.152.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts: 
        - react.212.2.242.152.sslip.io
      secretName: baseline-react-app-tls
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
