image:
  repository: ohmygaugh/baseline-react-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.

  tag: "20240429T231423"
imagePullSecrets: 
  - name: docker-pull-secret
service:
  type: ClusterIP
  port: 80
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: ws
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/websocket-routes: "/"
  hosts:
    - host: react.212.2.242.193.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts: 
        - react.212.2.242.193.sslip.io
      secretName: baseline-react-app-tls
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
env:
  - name: WDS_SOCKET_HOST
    value: "react.212.2.242.193.sslip.io"
  - name: WDS_SOCKET_PORT
    value: "443"
  - name: HTTPS
    value: "true"
