image:
  repository: ohmygaugh/baseline-react-app
  pullPolicy: Always
  tag: "YYYYMMDDTHHMMSS"
imagePullSecrets:
  - name: docker-push-user
service:
  type: ClusterIP
  port: 80
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/websocket-routes: "/"
  hosts:
    - host: react-prod.212.2.242.193.sslip.io
      paths:
        - path: /
          pathType: Prefix
        - path: /ws
          pathType: Prefix
  tls:
    - hosts:
        - react-prod.212.2.242.193.sslip.io
      secretName: baseline-react-app-tls